@startuml
'https://plantuml.com/class-diagram



Stack <|-- StackArray

interface Stack {
}



class StackArray<T> {
    - T[] stack
    - int index
    +boolean isEmpty()
    +boolean isFull()
    +int size()
    +void push(T element)
    +T peek()
    +T pop()
}


@enduml